# Generated by Django 3.0.3 on 2020-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('debit', models.FloatField(blank=True, default=None, null=True)),
                ('credit', models.FloatField(blank=True, default=None, null=True)),
                ('balance', models.FloatField(blank=True, default=None, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
